name: Windows CI

on:
  push

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, Win32]

    steps:
    - uses: actions/checkout@v3

    - name: Build ${{ matrix.platform }}
      run: |
        $vsroot = (Get-VisualStudioInstance).InstallationPath
        $devenv = join-path $vsroot "Common7\IDE\devenv.com"
        cd Windows/VisualStudio
        & $devenv quakespasm.sln /Upgrade
        & $devenv quakespasm.sln /Build "Release|${{ matrix.platform }}" /Project quakespasm-sdl2.vcxproj
        if (-not $?) { throw "Build failed" }
