name: Linux CI

on: 
  push

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - target: win32
            package: i686-win32

          - target: win64
            package: w64-x86-64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt update && sudo apt install gcc-mingw-w64-${{ matrix.config.package }}

      - name: Build with MinGW ${{ matrix.config.target }}
        run: |
          export QSS_CFLAGS="-DQSS_VERSION=$(git describe --always) -DQSS_REVISION=$(git rev-parse HEAD) -DQSS_DATE=$(git log -1 --date=short --format=%cd)"
          ./Quake/build_cross_${{ matrix.config.target }}-sdl2.sh
