name: Linux CI

on: 
  push

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang", "gcc"]

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt update && sudo apt install libmad0-dev libopusfile-dev libsdl2-dev libvorbis-dev

    - name: Configure with ${{ matrix.compiler }}
      run: cmake -DCMAKE_C_COMPILER=${{ matrix.compiler }} -B build

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build --parallel -- --keep-going
